### ISSUE TITLE
Gitignore is created in wrong project

### ISSUE THREAD

**Issue by textpain** [andydevs/auto-create-files#1]
It always writes freshly created files to my first opened projects in the projects pane. I have multiple projects opened and regardless of what of them I'm into right now (according to the Git pane) this extension always writes the file into the first project in the list.

**Comment by thumperward** [comment]
here's the culprit:

https://github.com/andydevs/auto-create-files/blob/master/lib/template-selector.coffee#L71

opened #2 which will select the present project directory if an existing file in it is open.

**Comment by thumperward** [comment]
now that the above has been merged, it should be okay to close this as fixed

**Comment by andydevs** [comment]
Fixed finally (It's been two months...)
